# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calc_msg_pb2 as calc__msg__pb2


class CalculatorStub(object):
    """缺陷报告查询服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calculate = channel.unary_unary(
                '/serviceImpl.Calculator/calculate',
                request_serializer=calc__msg__pb2.CalcRequest.SerializeToString,
                response_deserializer=calc__msg__pb2.CalcReply.FromString,
                )


class CalculatorServicer(object):
    """缺陷报告查询服务定义
    """

    def calculate(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.calculate,
                    request_deserializer=calc__msg__pb2.CalcRequest.FromString,
                    response_serializer=calc__msg__pb2.CalcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serviceImpl.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """缺陷报告查询服务定义
    """

    @staticmethod
    def calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serviceImpl.Calculator/calculate',
            calc__msg__pb2.CalcRequest.SerializeToString,
            calc__msg__pb2.CalcReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
