# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calc_msg.proto',
  package='serviceImpl',
  syntax='proto3',
  serialized_options=b'\n\035pgd.irbl.business.serviceImplB\014CalcMsgProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63\x61lc_msg.proto\x12\x0bserviceImpl\"9\n\x0b\x43\x61lcRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x17\n\x0f\x62ug_report_path\x18\x02 \x01(\t\"-\n\tFileScore\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"H\n\tCalcReply\x12\x0f\n\x07succeed\x18\x01 \x01(\x05\x12*\n\nevaluation\x18\x02 \x03(\x0b\x32\x16.serviceImpl.FileScore2M\n\nCalculator\x12?\n\tcalculate\x12\x18.serviceImpl.CalcRequest\x1a\x16.serviceImpl.CalcReply\"\x00\x42/\n\x1dpgd.irbl.business.serviceImplB\x0c\x43\x61lcMsgProtoP\x01\x62\x06proto3'
)




_CALCREQUEST = _descriptor.Descriptor(
  name='CalcRequest',
  full_name='serviceImpl.CalcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='serviceImpl.CalcRequest.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bug_report_path', full_name='serviceImpl.CalcRequest.bug_report_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=88,
)


_FILESCORE = _descriptor.Descriptor(
  name='FileScore',
  full_name='serviceImpl.FileScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='serviceImpl.FileScore.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='serviceImpl.FileScore.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=135,
)


_CALCREPLY = _descriptor.Descriptor(
  name='CalcReply',
  full_name='serviceImpl.CalcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeed', full_name='serviceImpl.CalcReply.succeed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evaluation', full_name='serviceImpl.CalcReply.evaluation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=209,
)

_CALCREPLY.fields_by_name['evaluation'].message_type = _FILESCORE
DESCRIPTOR.message_types_by_name['CalcRequest'] = _CALCREQUEST
DESCRIPTOR.message_types_by_name['FileScore'] = _FILESCORE
DESCRIPTOR.message_types_by_name['CalcReply'] = _CALCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcRequest = _reflection.GeneratedProtocolMessageType('CalcRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCREQUEST,
  '__module__' : 'calc_msg_pb2'
  # @@protoc_insertion_point(class_scope:serviceImpl.CalcRequest)
  })
_sym_db.RegisterMessage(CalcRequest)

FileScore = _reflection.GeneratedProtocolMessageType('FileScore', (_message.Message,), {
  'DESCRIPTOR' : _FILESCORE,
  '__module__' : 'calc_msg_pb2'
  # @@protoc_insertion_point(class_scope:serviceImpl.FileScore)
  })
_sym_db.RegisterMessage(FileScore)

CalcReply = _reflection.GeneratedProtocolMessageType('CalcReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCREPLY,
  '__module__' : 'calc_msg_pb2'
  # @@protoc_insertion_point(class_scope:serviceImpl.CalcReply)
  })
_sym_db.RegisterMessage(CalcReply)


DESCRIPTOR._options = None

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='serviceImpl.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='calculate',
    full_name='serviceImpl.Calculator.calculate',
    index=0,
    containing_service=None,
    input_type=_CALCREQUEST,
    output_type=_CALCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
