# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocess.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='preprocess.proto',
  package='serviceImpl',
  syntax='proto3',
  serialized_options=b'\n\035pgd.irbl.business.serviceImplB\017PreProcessProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10preprocess.proto\x12\x0bserviceImpl\"&\n\x11PreProcessRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\"\n\x0fPreProcessReply\x12\x0f\n\x07succeed\x18\x01 \x01(\x05\x32\x62\n\x0cPreProcessor\x12R\n\x10proto_preprocess\x12\x1e.serviceImpl.PreProcessRequest\x1a\x1c.serviceImpl.PreProcessReply\"\x00\x42\x32\n\x1dpgd.irbl.business.serviceImplB\x0fPreProcessProtoP\x01\x62\x06proto3'
)




_PREPROCESSREQUEST = _descriptor.Descriptor(
  name='PreProcessRequest',
  full_name='serviceImpl.PreProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='serviceImpl.PreProcessRequest.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=71,
)


_PREPROCESSREPLY = _descriptor.Descriptor(
  name='PreProcessReply',
  full_name='serviceImpl.PreProcessReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeed', full_name='serviceImpl.PreProcessReply.succeed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['PreProcessRequest'] = _PREPROCESSREQUEST
DESCRIPTOR.message_types_by_name['PreProcessReply'] = _PREPROCESSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PreProcessRequest = _reflection.GeneratedProtocolMessageType('PreProcessRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSREQUEST,
  '__module__' : 'preprocess_pb2'
  # @@protoc_insertion_point(class_scope:serviceImpl.PreProcessRequest)
  })
_sym_db.RegisterMessage(PreProcessRequest)

PreProcessReply = _reflection.GeneratedProtocolMessageType('PreProcessReply', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSREPLY,
  '__module__' : 'preprocess_pb2'
  # @@protoc_insertion_point(class_scope:serviceImpl.PreProcessReply)
  })
_sym_db.RegisterMessage(PreProcessReply)


DESCRIPTOR._options = None

_PREPROCESSOR = _descriptor.ServiceDescriptor(
  name='PreProcessor',
  full_name='serviceImpl.PreProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='proto_preprocess',
    full_name='serviceImpl.PreProcessor.proto_preprocess',
    index=0,
    containing_service=None,
    input_type=_PREPROCESSREQUEST,
    output_type=_PREPROCESSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREPROCESSOR)

DESCRIPTOR.services_by_name['PreProcessor'] = _PREPROCESSOR

# @@protoc_insertion_point(module_scope)
