# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import preprocess_pb2 as preprocess__pb2


class PreProcessorStub(object):
    """预处理服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.proto_preprocess = channel.unary_unary(
                '/ServiceImpl.PreProcessor/proto_preprocess',
                request_serializer=preprocess__pb2.PreProcessRequest.SerializeToString,
                response_deserializer=preprocess__pb2.PreProcessReply.FromString,
                )


class PreProcessorServicer(object):
    """预处理服务定义
    """

    def proto_preprocess(self, request, context):
        """preprocess
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'proto_preprocess': grpc.unary_unary_rpc_method_handler(
                    servicer.proto_preprocess,
                    request_deserializer=preprocess__pb2.PreProcessRequest.FromString,
                    response_serializer=preprocess__pb2.PreProcessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceImpl.PreProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PreProcessor(object):
    """预处理服务定义
    """

    @staticmethod
    def proto_preprocess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServiceImpl.PreProcessor/proto_preprocess',
            preprocess__pb2.PreProcessRequest.SerializeToString,
            preprocess__pb2.PreProcessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
