spring:
  profiles:
    active: dev



file:
  path:
    code: "/Users/pkun/IdeaProjects/backend-irbl/data/source-code/"
    report: "/Users/pkun/IdeaProjects/backend-irbl/data/report/"
    python-cache: "/Users/pkun/IdeaProjects/backend-irbl/data/python-cache/"