spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


#file:
#  path:
#    code: "/Users/pkun/IdeaProjects/backend-irbl/data/source-code/"
#    report: "/Users/pkun/IdeaProjects/backend-irbl/data/report/"
#    python-cache: "/Users/pkun/IdeaProjects/backend-irbl/data/python-cache/"

file:
  path:
    code: "/data/source-code/"
    report: "/data/report/"
    python-cache: "/data/python-cache/"

cpu:
  core: 2