spring:
  profiles:
    active: dev


server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: li2000chun
    key-store-type: PKCS12
    key-alias: irbl

file:
  path:
    code: "/data/source-code/"
    report: "/data/report/"
    python-cache: "/data/python-cache/"