spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


file:
  path:
    code: "/data/source-code/"
    report: "/data/report/"
    python-cache: "/data/python-cache/"