// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc_msg.proto

package pgd.irbl.business.serviceImpl;

public interface CalcReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceImpl.CalcReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 succeed = 1;</code>
   * @return The succeed.
   */
  int getSucceed();

  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  java.util.List<FileScore>
      getEvaluationList();
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  FileScore getEvaluation(int index);
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  int getEvaluationCount();
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  java.util.List<? extends FileScoreOrBuilder>
      getEvaluationOrBuilderList();
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  FileScoreOrBuilder getEvaluationOrBuilder(
      int index);
}
