// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc_msg.proto

package pgd.irbl.business.serviceImpl;

/**
 * <pre>
 * 计算后返回的参数
 * </pre>
 *
 * Protobuf type {@code serviceImpl.CalcReply}
 */
public final class CalcReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serviceImpl.CalcReply)
    CalcReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalcReply.newBuilder() to construct.
  private CalcReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalcReply() {
    evaluation_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CalcReply();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalcReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            succeed_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              evaluation_ = new java.util.ArrayList<FileScore>();
              mutable_bitField0_ |= 0x00000001;
            }
            evaluation_.add(
                input.readMessage(FileScore.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        evaluation_ = java.util.Collections.unmodifiableList(evaluation_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CalcMsgProto.internal_static_serviceImpl_CalcReply_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CalcMsgProto.internal_static_serviceImpl_CalcReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CalcReply.class, Builder.class);
  }

  public static final int SUCCEED_FIELD_NUMBER = 1;
  private int succeed_;
  /**
   * <code>int32 succeed = 1;</code>
   * @return The succeed.
   */
  @Override
  public int getSucceed() {
    return succeed_;
  }

  public static final int EVALUATION_FIELD_NUMBER = 2;
  private java.util.List<FileScore> evaluation_;
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  @Override
  public java.util.List<FileScore> getEvaluationList() {
    return evaluation_;
  }
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  @Override
  public java.util.List<? extends FileScoreOrBuilder>
      getEvaluationOrBuilderList() {
    return evaluation_;
  }
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  @Override
  public int getEvaluationCount() {
    return evaluation_.size();
  }
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  @Override
  public FileScore getEvaluation(int index) {
    return evaluation_.get(index);
  }
  /**
   * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
   */
  @Override
  public FileScoreOrBuilder getEvaluationOrBuilder(
      int index) {
    return evaluation_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (succeed_ != 0) {
      output.writeInt32(1, succeed_);
    }
    for (int i = 0; i < evaluation_.size(); i++) {
      output.writeMessage(2, evaluation_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (succeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, succeed_);
    }
    for (int i = 0; i < evaluation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, evaluation_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CalcReply)) {
      return super.equals(obj);
    }
    CalcReply other = (CalcReply) obj;

    if (getSucceed()
        != other.getSucceed()) return false;
    if (!getEvaluationList()
        .equals(other.getEvaluationList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCEED_FIELD_NUMBER;
    hash = (53 * hash) + getSucceed();
    if (getEvaluationCount() > 0) {
      hash = (37 * hash) + EVALUATION_FIELD_NUMBER;
      hash = (53 * hash) + getEvaluationList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CalcReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalcReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalcReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalcReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalcReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalcReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalcReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalcReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalcReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CalcReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalcReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalcReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CalcReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 计算后返回的参数
   * </pre>
   *
   * Protobuf type {@code serviceImpl.CalcReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serviceImpl.CalcReply)
      CalcReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalcMsgProto.internal_static_serviceImpl_CalcReply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalcMsgProto.internal_static_serviceImpl_CalcReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalcReply.class, Builder.class);
    }

    // Construct using pgd.irbl.business.serviceImpl.CalcReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEvaluationFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      succeed_ = 0;

      if (evaluationBuilder_ == null) {
        evaluation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        evaluationBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CalcMsgProto.internal_static_serviceImpl_CalcReply_descriptor;
    }

    @Override
    public CalcReply getDefaultInstanceForType() {
      return CalcReply.getDefaultInstance();
    }

    @Override
    public CalcReply build() {
      CalcReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CalcReply buildPartial() {
      CalcReply result = new CalcReply(this);
      int from_bitField0_ = bitField0_;
      result.succeed_ = succeed_;
      if (evaluationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          evaluation_ = java.util.Collections.unmodifiableList(evaluation_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.evaluation_ = evaluation_;
      } else {
        result.evaluation_ = evaluationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CalcReply) {
        return mergeFrom((CalcReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CalcReply other) {
      if (other == CalcReply.getDefaultInstance()) return this;
      if (other.getSucceed() != 0) {
        setSucceed(other.getSucceed());
      }
      if (evaluationBuilder_ == null) {
        if (!other.evaluation_.isEmpty()) {
          if (evaluation_.isEmpty()) {
            evaluation_ = other.evaluation_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEvaluationIsMutable();
            evaluation_.addAll(other.evaluation_);
          }
          onChanged();
        }
      } else {
        if (!other.evaluation_.isEmpty()) {
          if (evaluationBuilder_.isEmpty()) {
            evaluationBuilder_.dispose();
            evaluationBuilder_ = null;
            evaluation_ = other.evaluation_;
            bitField0_ = (bitField0_ & ~0x00000001);
            evaluationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEvaluationFieldBuilder() : null;
          } else {
            evaluationBuilder_.addAllMessages(other.evaluation_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CalcReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CalcReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int succeed_ ;
    /**
     * <code>int32 succeed = 1;</code>
     * @return The succeed.
     */
    @Override
    public int getSucceed() {
      return succeed_;
    }
    /**
     * <code>int32 succeed = 1;</code>
     * @param value The succeed to set.
     * @return This builder for chaining.
     */
    public Builder setSucceed(int value) {
      
      succeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 succeed = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSucceed() {
      
      succeed_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<FileScore> evaluation_ =
      java.util.Collections.emptyList();
    private void ensureEvaluationIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        evaluation_ = new java.util.ArrayList<FileScore>(evaluation_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        FileScore, FileScore.Builder, FileScoreOrBuilder> evaluationBuilder_;

    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public java.util.List<FileScore> getEvaluationList() {
      if (evaluationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(evaluation_);
      } else {
        return evaluationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public int getEvaluationCount() {
      if (evaluationBuilder_ == null) {
        return evaluation_.size();
      } else {
        return evaluationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public FileScore getEvaluation(int index) {
      if (evaluationBuilder_ == null) {
        return evaluation_.get(index);
      } else {
        return evaluationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder setEvaluation(
        int index, FileScore value) {
      if (evaluationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvaluationIsMutable();
        evaluation_.set(index, value);
        onChanged();
      } else {
        evaluationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder setEvaluation(
        int index, FileScore.Builder builderForValue) {
      if (evaluationBuilder_ == null) {
        ensureEvaluationIsMutable();
        evaluation_.set(index, builderForValue.build());
        onChanged();
      } else {
        evaluationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder addEvaluation(FileScore value) {
      if (evaluationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvaluationIsMutable();
        evaluation_.add(value);
        onChanged();
      } else {
        evaluationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder addEvaluation(
        int index, FileScore value) {
      if (evaluationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvaluationIsMutable();
        evaluation_.add(index, value);
        onChanged();
      } else {
        evaluationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder addEvaluation(
        FileScore.Builder builderForValue) {
      if (evaluationBuilder_ == null) {
        ensureEvaluationIsMutable();
        evaluation_.add(builderForValue.build());
        onChanged();
      } else {
        evaluationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder addEvaluation(
        int index, FileScore.Builder builderForValue) {
      if (evaluationBuilder_ == null) {
        ensureEvaluationIsMutable();
        evaluation_.add(index, builderForValue.build());
        onChanged();
      } else {
        evaluationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder addAllEvaluation(
        Iterable<? extends FileScore> values) {
      if (evaluationBuilder_ == null) {
        ensureEvaluationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, evaluation_);
        onChanged();
      } else {
        evaluationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder clearEvaluation() {
      if (evaluationBuilder_ == null) {
        evaluation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        evaluationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public Builder removeEvaluation(int index) {
      if (evaluationBuilder_ == null) {
        ensureEvaluationIsMutable();
        evaluation_.remove(index);
        onChanged();
      } else {
        evaluationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public FileScore.Builder getEvaluationBuilder(
        int index) {
      return getEvaluationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public FileScoreOrBuilder getEvaluationOrBuilder(
        int index) {
      if (evaluationBuilder_ == null) {
        return evaluation_.get(index);  } else {
        return evaluationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public java.util.List<? extends FileScoreOrBuilder>
         getEvaluationOrBuilderList() {
      if (evaluationBuilder_ != null) {
        return evaluationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(evaluation_);
      }
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public FileScore.Builder addEvaluationBuilder() {
      return getEvaluationFieldBuilder().addBuilder(
          FileScore.getDefaultInstance());
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public FileScore.Builder addEvaluationBuilder(
        int index) {
      return getEvaluationFieldBuilder().addBuilder(
          index, FileScore.getDefaultInstance());
    }
    /**
     * <code>repeated .serviceImpl.FileScore evaluation = 2;</code>
     */
    public java.util.List<FileScore.Builder>
         getEvaluationBuilderList() {
      return getEvaluationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        FileScore, FileScore.Builder, FileScoreOrBuilder>
        getEvaluationFieldBuilder() {
      if (evaluationBuilder_ == null) {
        evaluationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            FileScore, FileScore.Builder, FileScoreOrBuilder>(
                evaluation_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        evaluation_ = null;
      }
      return evaluationBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serviceImpl.CalcReply)
  }

  // @@protoc_insertion_point(class_scope:serviceImpl.CalcReply)
  private static final CalcReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CalcReply();
  }

  public static CalcReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalcReply>
      PARSER = new com.google.protobuf.AbstractParser<CalcReply>() {
    @Override
    public CalcReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalcReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalcReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CalcReply> getParserForType() {
    return PARSER;
  }

  @Override
  public CalcReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

