// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc_msg.proto

package pgd.irbl.business.serviceImpl;

public interface CalcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceImpl.CalcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * project root file path
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  String getFilePath();
  /**
   * <pre>
   * project root file path
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <pre>
   * bug report path
   * </pre>
   *
   * <code>string bug_report_path = 2;</code>
   * @return The bugReportPath.
   */
  String getBugReportPath();
  /**
   * <pre>
   * bug report path
   * </pre>
   *
   * <code>string bug_report_path = 2;</code>
   * @return The bytes for bugReportPath.
   */
  com.google.protobuf.ByteString
      getBugReportPathBytes();
}
