// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preprocess.proto

package pgd.irbl.business.serviceImpl;

public final class PreProcessProto {
  private PreProcessProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceImpl_PreProcessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serviceImpl_PreProcessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceImpl_PreProcessReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serviceImpl_PreProcessReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020preprocess.proto\022\013serviceImpl\"&\n\021PrePr" +
      "ocessRequest\022\021\n\tfile_path\030\001 \001(\t\"\"\n\017PrePr" +
      "ocessReply\022\017\n\007succeed\030\001 \001(\0052b\n\014PreProces" +
      "sor\022R\n\020proto_preprocess\022\036.serviceImpl.Pr" +
      "eProcessRequest\032\034.serviceImpl.PreProcess" +
      "Reply\"\000B2\n\035pgd.irbl.business.serviceImpl" +
      "B\017PreProcessProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_serviceImpl_PreProcessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serviceImpl_PreProcessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serviceImpl_PreProcessRequest_descriptor,
        new String[] { "FilePath", });
    internal_static_serviceImpl_PreProcessReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serviceImpl_PreProcessReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serviceImpl_PreProcessReply_descriptor,
        new String[] { "Succeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
