// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preprocess.proto

package pgd.irbl.business.serviceImpl;

public interface PreProcessReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceImpl.PreProcessReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 succeed = 1;</code>
   * @return The succeed.
   */
  int getSucceed();
}
