// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preprocess.proto

package pgd.irbl.business.serviceImpl;

public interface PreProcessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceImpl.PreProcessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * project root file path
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  String getFilePath();
  /**
   * <pre>
   * project root file path
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
