// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc_msg.proto

package pgd.irbl.business.serviceImpl.protobuf;

public interface FileScoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceImpl.FileScore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  String getFilePath();
  /**
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <code>double score = 2;</code>
   * @return The score.
   */
  double getScore();
}
